configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-san-francisco-compute-company%2Fsfc-nodes-51beb0e3e65eab042753ff6abb89ed40d167bd16ee67cdd213cab30219bec224.yml
openapi_spec_hash: 7526ea7dd36fca1d0850e8a1b109b249
config_hash: ada4ea3670884e51d3b5b4f3b5a6e76d
