configured_endpoints: 13
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-san-francisco-compute-company%2Fsfc-nodes-80cab7746a6cdf7657e218c427ff7e13db1ac2454eacaccf0f36120234d49a3d.yml
openapi_spec_hash: c36b216292e88e7bd8d57ef05cf67cf2
config_hash: 5ab998e0c5691df351205dfc14a2cfaf
